name: pomocnik_wokalisty
description: "Pomocnik wokalisty"
publish_to: 'none'

version: 0.9.4+8

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async_preferences: ^2.0.0
  auto_size_text: ^3.0.0
  chaleno: ^0.0.8
  collection: ^1.18.0
  connectivity_plus: ^7.1.1
  country_flags: ^4.0.1
  cupertino_icons: ^1.0.8
  encoder: ^1.0.0
  equatable: ^2.0.7
  events_emitter: ^0.6.0
  file_picker: ^12.0.0-beta.5
  flutter_app_name_localization: ^0.1.0
  flutter_bloc: ^9.0.0
  flutter_debouncer: ^2.0.0
  flutter_fullscreen: ^1.2.0
  flutter_markdown_plus: ^1.0.7
  fluttertoast: ^9.1.0
  future_progress_dialog: ^0.2.1
  get_it: ^9.2.1
  google_mobile_ads: ^8.0.0
  hive_ce_flutter: ^2.3.4
  intl: any
  just_audio: ^0.10.5
  mobile_scanner: ^7.2.0
  nested: ^1.0.0
  network_info_plus: ^8.1.0
  package_info_plus: ^10.1.0
  paginated_text: ^0.4.5
  path_provider: ^2.1.0
  qr_flutter: ^4.1.0
  record: ^7.0.0
  shared_preferences: ^2.5.3
  standard_searchbar: ^2.1.1
  stream_transform: ^2.1.0
  uuid: ^4.5.1
  youtube_explode_dart: ^3.1.0
  http: ^1.4.0
  hive_ce: ^2.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.8.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo/logo.png
    - assets/images/icons/connectionSettings.png
    - assets/images/icons/delete.png
    - assets/images/icons/downArrow.png
    - assets/images/icons/edit.png
    - assets/images/icons/minus.png
    - assets/images/icons/note.png
    - assets/images/icons/playlist.png
    - assets/images/icons/plus.png
    - assets/images/icons/plusRed.png
    - assets/images/icons/presentation.png
    - assets/images/icons/save.png
    - assets/images/icons/search.png
    - assets/images/icons/selected_circle.png
    - assets/images/icons/settings.png
    - assets/images/icons/unselected_circle.png
    - assets/images/icons/upArrow.png
    - assets/markdown/privacy_policy_en.md
    - assets/markdown/privacy_policy_pl.md
    - assets/markdown/terms_and_conditions_en.md
    - assets/markdown/terms_and_conditions_pl.md

  generate: true

flutter_app_name_localization:
  default: "Singer assistant"
  locales:
    - locale: "en"
      name: "Singer assistant"
    - locale: "pl"
      name: "Pomocnik wokalisty"

flutter_icons:
  image_path: "assets/images/logo/logo.png"
  android: true
  ios: true
